Issue #BIB-257: Changed how tags are read
bibboxen/bibbox-rfid pull request #11
Opened 2017-04-19 13:56 UTC by tuj

2017-04-19 17:42 UTC, cableman requested changes
Just some minor missing comments to make it more clear! :-)

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
> +	 *            The tag listener where reader events are passed to.
Why the spacing in the comments here?

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
> +			int threadSleepInMillis) {
Not fan of the parameters on the next line thing, but it's up to you!

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
>  		fedm.readReaderInfo();
I see not reader type setting here as the comment say? Is it a side effect of "readReaderInfo"?

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
> +	protected HashMap<String, BibTag> getTags() throws FedmException, FePortDriverException, FeReaderDriverException {
It's hard to see in the diff... is this missing a documentation block?

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
> +			th = fedm.tagSelect(th, tagDriver);
What is "e" - event?

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
> +			if (th instanceof FedmIscTagHandler_ISO15693) {
Maybe a comment about that we limit the reading to ISO15693 tags!

2017-04-19 17:42 UTC, cableman commented on src/readers/FeigReader.java
> +				if (back == 0) {
Should the variable "back" have been "block"? If not what do "back" mean in this context!

2017-04-19 18:55 UTC, tuj commented on src/readers/FeigReader.java
>  		fedm.readReaderInfo();
Removed

2017-04-19 18:56 UTC, tuj commented on src/readers/FeigReader.java
> +	protected HashMap<String, BibTag> getTags() throws FedmException, FePortDriverException, FeReaderDriverException {
Fixed

2017-04-19 18:57 UTC, tuj commented on src/readers/FeigReader.java
> +			th = fedm.tagSelect(th, tagDriver);
fixed

2017-04-19 19:15 UTC, tuj commented on src/readers/FeigReader.java
> +			if (th instanceof FedmIscTagHandler_ISO15693) {
I actually don't think it is necessary

2017-04-19 19:15 UTC, tuj commented on src/readers/FeigReader.java
> +				if (back == 0) {
Renamed to dataReadSuccess

2017-04-19 19:16 UTC, tuj commented on src/readers/FeigReader.java
> +			int threadSleepInMillis) {
Fixed, result of auto-format

2017-04-19 19:16 UTC, tuj commented on src/readers/FeigReader.java
> +	 *            The tag listener where reader events are passed to.
Fixed, result of auto-format

2017-04-20 06:46 UTC, tuj commented
@cableman 
Added comment about comment :)
Added fix to crc check that resulted in rejected materials

2017-04-20 17:19 UTC, cableman approved these changes

2017-04-20 17:21 UTC, cableman requested changes

2017-04-20 17:21 UTC, cableman commented on src/middleware/AbstractTagReader.java
> +		crc = (crc.substring(2, 4) + crc.substring(0, 2)).replaceFirst("^0+(?!$)", "");
Should this replace not be done on both CRC substrings?

2017-04-20 17:33 UTC, cableman approved these changes

2017-04-20 17:33 UTC, merged